# Generated by Django 5.1.3 on 2024-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
