# Generated by Django 5.1.3 on 2024-11-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scrapeddata_id_alter_scrapeddata_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='photo_url',
            new_name='image',
        ),
    ]
