# Generated by Django 5.1.3 on 2024-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_photo_url_scrapeddata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='image',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
