# Generated by Django 5.1.3 on 2024-12-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_scrapeddata_email_remove_scrapeddata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='address',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
