# Generated by Django 5.1.3 on 2024-12-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_scrapeddata_address_alter_scrapeddata_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
